### ISSUE TITLE
Problem with class 'Player'

### ISSUE THREAD

**Issue by thecogdoctor** [thecogdoctor/ArenaGame#3]
[Player.h](https://github.com/thecogdoctor/ArenaGame/blob/master/Player.h) 
[Player.cpp](https://github.com/thecogdoctor/ArenaGame/blob/master/Player.cpp)
[ArenaGame.ino](https://github.com/thecogdoctor/ArenaGame/blob/master/ArenaGame.ino)
I have found the root of my previous problem, but it comes in two forms, currentPlayer being in the loop means the player character can only move to 41 or 39, and putting currentPlayer's initialization above setup and loop causes the entire thing to break, it will compile but it will not actually print anything to the screen or the serial monitor. 
```cpp
###############################
 //This code does not work!! 
(Code taken from ArenaGame.ino)   
###############################
#define PSX 40  //PSX = Player Start X (Position)
#define PSY 125 //PSY = Player Start Y (Position)

bool running = false;

FancyDelay displayWaitTime(1000);

Player currentPlayer(PSX, PSY);

void setup()
{
	Serial.begin(115200); //Serial Start
	Serial.println("Setup Function\n");
	Startup();
	Dungeon();
}

void loop()
{
	if(displayWaitTime.ready() && running == false)
    {
    	Serial.println("Main Loop\n");
        running = true;
    }
    
    if(running)
    {
        currentPlayer.Render('@');
    }
}
```

```cpp
####################################
// This code does work, but not as intended 
(Code taken from ArenaGame.ino)                     
####################################
#define PSX 40  //PSX = Player Start X (Position)
#define PSY 125 //PSY = Player Start Y (Position)

bool running = false;

FancyDelay displayWaitTime(1000);

//Player currentPlayer(PSX, PSY);

void setup()
{
	Serial.begin(115200); //Serial Start
	Serial.println("Setup Function\n");
	Startup();
	Dungeon();
}

void loop()
{
	if(displayWaitTime.ready() && running == false)
    {
    	Serial.println("Main Loop\n");
        running = true;
    }
    
    if(running)
    {
    	Player currentPlayer(PSX, PSY);
        currentPlayer.Render('@');
    }
}
```

**Comment by Unchapped** [comment]
Not sure what the problem is, but I think it may be are calling int activeDirection = JoyStickCheck(ANALOGDEBUG); in your player class definition, so that you can't actually instantiate this class outside of an active running scope where JoyStickCheck can be called, activedirection should be an argument to the render() method, not called in your class definition.

What I would recommend is a few structural changes to your Player class. I'm assuming that the player is not the only thing you'll want to draw on the screen, so I would change it to a more general 'sprite' class that stores its X, Y position and representative character '@', this could be constructed outside of active scope.

Then I would split your 'render' function into two separate functions: 'move(relative_x, relative_y)' which updates the sprite's internal location model. and 'render(AdafruitGFX tft)' which draws it on the screen (but does not erase the previous location).

Then in your main .ino code (or in a Sprites.cpp file or similar), I would add

```
Sprite player = Sprite(startX, startY, '@');
Sprite monster = Sprite(x2, y2, '#'); //for example

Sprite *sprites[] = {player, monster}; //This is an array of pointers, see: http://www.cplusplus.com/doc/tutorial/pointers/
```

and restructure your loop like so (pseudocode, not correct or complete syntax):

```
loop(){
	//parse joystick input, mabe move this to a function to keep your code neat.
	switch(JoyStickCheck(ANALOGDEBUG)):
		case Up:
			player.move(0,1);
		case Down:
			player.move(0,-1):
		//...etc.
	//update Monster positions
		//AI code goes here, moving the monster sprites
	
	//redraw the screen
	tft.clear() //erase everything
	for sprite in sprites:
		sprite.render(tft)
```

**Comment by thecogdoctor** [comment]
Fixed this issue specifically. Minor bugs will be noted in next issue.
